services:
    postgis:
        image: postgis/postgis:latest
        environment:
            POSTGRES_DB: o2p
            POSTGRES_USER: o2p
            POSTGRES_PASSWORD: o2p
        volumes:
            - ./data/postgis:/var/lib/postgresql/data
        healthcheck:
            test: pg_isready -h localhost -d o2p -U o2p
            start_period: 60s
            start_interval: 1s
        restart: always

    osm2pgsql:
        image: iboates/osm2pgsql
        volumes:
            - .:/styles:ro
            - ./data/osm2pgsql:/data
        environment:
            PGHOST: postgis
            PGDATABASE: o2p
            PGUSER: o2p
            PGPASSWORD: o2p
            OSM2PGSQL_ARGS: -O flex -S /styles/main.lua --slim
            #OSM2PGSQL_ARGS: -O flex -S /styles/main.lua --slim --flat-nodes /data/flat_nodes.bin
        links:
            - postgis
        depends_on:
            postgis:
                condition: service_healthy
        entrypoint: ""
        command: sh -c 'while true; do osm2pgsql-replication update -- $$OSM2PGSQL_ARGS; sleep 300; done'
        restart: always

    import:
        extends: osm2pgsql
        volumes:
            - ./region.osm.pbf:/region.osm.pbf:ro
        command: sh -c 'osm2pgsql $$OSM2PGSQL_ARGS /region.osm.pbf'
        profiles: [import]

    tileserver:
        image: facilmap/openstreetmap-tile-server
        environment:
            ALLOW_CORS: enabled
            DEMO_VISIBLE: 0
            DEMO_MAPNIK: 2
            DEMO_OPACITY: 0.7
        volumes:
            - ./data/tileserver:/data
            - ./cobblestone/style:/style/cobblestone:ro
            - ./cycling-restrictions/style:/style/cycling-restrictions:ro
            - ./tolls/style:/style/tolls:ro
        links:
            - postgis
        depends_on:
            postgis:
                condition: service_healthy
        ports:
            - 8080:80
        restart: always